# Created using 
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: WingetCreateE2E.Yaml.ZipTest
PackageVersion: 1.2.3.4
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: msi
NestedInstallerFiles:
- RelativeFilePath: WingetCreateTestMsiInstaller.msi
ProductCode: '{E2650EFC-DCD3-4FAA-BBAC-FD1812B03A61}'
Installers:
- Architecture: x64
  InstallerUrl: https://fakedomain.com/WingetCreateTestZipInstaller.zip
  InstallerSha256: 1214B8F15CBB243AD3A3DD76F8835AF3AA0942689750102F3B7740B782A7B2D2
ManifestType: installer
ManifestVersion: 1.12.0
